### ISSUE TITLE
feat: add review text input prior to reviewTask

### ISSUE THREAD

**Issue by 0xneves** [w3b3d3v/web3task-front#105]
Proposal:
- Make a modal to paste a review prior to sending it. Can be a popup when hover, and close when get out of the box. Or any other novel idea!! 
- The review must be used in the `reviewTask` function as the third parameter.
- Empty review notes should be discouraged (min 30 letters)

**Comment by heronlancellot** [comment]
Hey @0xneves I will handle that one 👍
