### ISSUE TITLE
Feat: Change the ethers to viem + wagmi + rainbow

### ISSUE THREAD

**Issue by heronlancellot** [w3b3d3v/web3task-front#137]

**Comment by diegosano** [comment]
@heronlancellot Can I work on this issue?

**Comment by heronlancellot** [comment]
Assigned to you !

**Comment by heronlancellot** [comment]
Initial structure of viem + wagmi by commit 88ca9cde9db4cff84ae83962ba3bbf287131f5e2
need adjust the types to call the task-service

**Comment by heronlancellot** [comment]
Closed by #164
