### ISSUE TITLE
refactor: Material UI to Tailwind & Create Components

### ISSUE THREAD

**Issue by heronlancellot** [w3b3d3v/web3task-front#139]
This task should be fragmented in others Tasks to create components using the tailwind 

Like:

- [x] #140 
- [x] #143 
- [x] #144 
- [x] #145

**Comment by 0xneves** [comment]
[This issue](https://github.com/w3b3d3v/web3task-lp/issues/1) is blocking further development of this issue:

**Comment by Guboehm** [comment]
Task completed.
