### ISSUE TITLE
Refactor: Pages to the new APP Router Configuration

### ISSUE THREAD

**Issue by heronlancellot** [w3b3d3v/web3task-front#140]
This task will refactor the pages in application in the new way ( app router )

**Comment by Guboehm** [comment]
Task completed in the deliveries above.
[Feat/140 refactor structure #149](https://github.com/w3b3d3v/web3task-front/pull/149)
[Feat/atomic design #166](https://github.com/w3b3d3v/web3task-front/pull/166)
