### ISSUE TITLE
Ask to change the metamask network if you have one where there is no task.

### ISSUE THREAD

**Issue by viniblack** [w3b3d3v/web3task-front#141]
When I go to the [vercel site](https://web3task-front.vercel.app/) and my metamask is on a network where we don't have the contract deployed, the application tries to load the tasks, but since there is no task, nothing appears.
Shouldn't we check if the user's metamask is on the network where we have the contract deployed, and if not, a message appears asking him to switch to the network where we have the task. 

<a href="https://github.com/w3b3d3v/web3task-front/assets/51183682/a9d5b695-b095-4e01-8e74-bf14033e98a1" target="_blank">I have recorded a video to demonstrate what I am talking about.</a>

1 - In the video I started with my metamask on the **Ethereum Mainnet** network and entered the site where it tried to load the tasks, but since we don't have the contract on that network it doesn't load any tasks.
2 - I then switched to the Mumbai network where we have tasks registered and those tasks appeared on the front end.

Instead of not loading anything if I'm on the wrong network, it should ask me to switch to a network where it has the task.

**Comment by Guboehm** [comment]
At the moment it doesn't make sense for the project
