### ISSUE TITLE
Do I have to be logged in to see information about a task?

### ISSUE THREAD

**Issue by viniblack** [w3b3d3v/web3task-front#142]
Thinking about the best usability of the platform, shouldn't I be able to see the information of a task without being connected to the platform?

<a href="https://github.com/w3b3d3v/web3task-front/assets/51183682/93d8c6f1-c114-48f3-9620-e462a27e4380" target="_blank">I have recorded a video to demonstrate what I am talking about.</a>

When I think about it, I should only need to be logged into the platform when I'm interacting with the task; I shouldn't need to be logged in just to view the information.

If I need to be logged into the platform to see the task information, then a message should be displayed to the user when I click on a task instead of trying to load the task information and ending up back at home.

**Comment by Guboehm** [comment]
At the moment it doesn't make sense for the project
