### ISSUE TITLE
Refactor: Icon Library to only one to working good with Tailwind + Next

### ISSUE THREAD

**Issue by heronlancellot** [w3b3d3v/web3task-front#143]
Proposal: 

- We currently use in repository 2 Libraries to create icons:
	- @mui/icons-material
	- react-icons/
- [ ]  Remove those currently Librarys
- [ ] Change the Icons to only one Library 
 
 Suggestions:
- [Heroicons]( https://heroicons.com/ )  | [React-Icons](https://react-icons.github.io/react-icons/)

Or suggest a better one ! 
### _Attention_ 
This task should be pushed to the **Next.js** _refactoring_ **branch** #16

**Comment by diegosano** [comment]
@heronlancellot Hey, can I work on this task?

**Comment by diegosano** [comment]
Also, I have a suggestion of the icons library, https://lucide.dev/ work well with tailwind and next

**Comment by heronlancellot** [comment]
Hey @diegosano assigned to you !

**Comment by heronlancellot** [comment]
closed by #156
