### ISSUE TITLE
feat: Refactor the dark-light theme from material ui to Tailwind CSS

### ISSUE THREAD

**Issue by heronlancellot** [w3b3d3v/web3task-front#146]
Proposal: 
- We currently use the themes with Material Ui
_Import Example:_
```
 import { alpha, createTheme, lighten, darken } from "@mui/material";
```

- [ ] Remove the Material UI Theme
- [ ] Create the theme with the Tailwind

[#9](https://github.com/w3b3d3v/web3task-org/issues/9)
### _Attention_ 
This task should be pushed to the **Next.js** _refactoring_ **branch** #16

**Comment by Guboehm** [comment]
At the moment it doesn't make sense for the project
