### ISSUE TITLE
epic: add rainbow wallet support or suggest a better one

### ISSUE THREAD

**Issue by 0xneves** [w3b3d3v/web3task-front#15]
We are currently not using a connect wallet out-of-the-box library like Rainbow wallet

Would be perfect to have a decent combination of viem+wagmi+rainbow or any other wallet provider that can allow for multiple types of wallets with close to 0 trouble when using it

Proposal:
- Refactor the entire Wallet experience of the users
- Refactor wallet usage, then re-test all transactions of the Web3Task Contracts

**Comment by 0xneves** [comment]
Looking forward for one that accepts phantom wallet for the Solana blockchain

**Comment by diegosano** [comment]
Connectkit is a good option and has translation to pt-br
https://docs.family.co/connectkit

**Comment by 0xneves** [comment]
Wow @diegosano this library looks very swiiiiiift, it flows! I like it, we previously had troubles with Viem + Wagmi, do you think you would have trouble trying to implement this? If you have interest in taking this task, please let me know!

**Comment by diegosano** [comment]
Hey @0xneves , I already have worked on projects using Wagmi + Ethers, and recently Wagmi + Viem, I think Viem is the "future", it is lightweight and has great performance. The Wagmi team is the same as Viem!
Also, the new versions of Wagmi, RainbowKit, and ConnectKit use Viem. If you guys don't have an interest in using Viem at the moment, we can use previous versions of Wagmi, RainbowKit/ConnectKit that have support for Ethers.

**Comment by 0xneves** [comment]
We surely want this!!  @diegosano 

But due to the Solana Hackathon getting closer we'll give priority to the MVP as a custom wallet made by us, and after that, the first thing we'll do is implement the MVP  into this boilerplate: https://github.com/blockful-io/frontend-web3-boilerplate

If you want to give it a try it uses NEXT + REACT + VIEM + RAINBOW

Works like a charm!

**Comment by 0xneves** [comment]
I'm closing this as it is already specified in the new version being built with Next #135
