### ISSUE TITLE
feat: migrate the roadmap from the pitch into the figma

### ISSUE THREAD

**Issue by 0xneves** [w3b3d3v/web3task-front#152]
The following is the Roadmap example:
![Image](https://github.com/w3b3d3v/web3task-front/assets/90667119/5e279d56-f072-4cd3-8eff-16213c4e6ab4)

Get the information about the project roadmap in the pitch and migrate it to the section above.

**Comment by 0xneves** [comment]
The pitch is here: https://www.canva.com/design/DAFxSNipyGo/n1CFy1HHW04Lf1fcublKRg/edit?utm_content=DAFxSNipyGo&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

**Comment by 0xdev3dl** [comment]
![roadmap 1](https://github.com/w3b3d3v/web3task-front/assets/101841063/6a967ab5-68f5-47c1-939a-3c9dd3f7f97c)
standardization of LP colors

**Comment by 0xneves** [comment]
Duplicated. I'm closing this and moved to this [issue](https://github.com/w3b3d3v/web3task-org/issues/24)
