### ISSUE TITLE
feat: Add an environment file to the frontend

### ISSUE THREAD

**Issue by RafaDSan** [w3b3d3v/web3task-front#157]
Create an environment file to the root directory of the frontend to hide sensitive data.

**Comment by 0xneves** [comment]
Which are the variables we need to hide?

**Comment by RafaDSan** [comment]
> Which are the variables we need to hide?
Hey @0xneves. The `AUTHORIZATION_kEY` and `ENDPOINT_URL` from subgraph to call the API from the frontend

**Comment by 0xneves** [comment]
Closing this as it was fixed by #154
