### ISSUE TITLE
epic: Refactor the project into NEXT+REACT+TailWind

### ISSUE THREAD

**Issue by 0xneves** [w3b3d3v/web3task-front#16]
Proposal:
- Refactor the entire repository using NEXT to turn the react website static and faster

This is a very heavy task and should be broken into more pieces. Blockful have a  public repository with a very light front-end already using NEXT+REACT+RAINBOW+WAGMI+VIEM, which should be explored for this integration: https://github.com/blockful-io/frontend-web3-boilerplate

#15 Should work alongside this task because both of them achieves the same ecosystem

**Comment by diegosano** [comment]
I would like to work in this task if is open 😄

**Comment by diegosano** [comment]
@heronlancellot hey, can I work with you on this task?

**Comment by heronlancellot** [comment]
Hey @diegosano, off course ! Let's handle that one

**Comment by 0xneves** [comment]
Any updates on this task?

**Comment by 0xneves** [comment]
I'm bumping this for updates once more @diegosano @heronlancellot 
We should sync next week, contact me!

**Comment by diegosano** [comment]
Sure, we can schedule a call to review together what is missing from this task to finalize!

**Comment by heronlancellot** [comment]
yupp ! Let's schedule a call @0xneves

**Comment by 0xneves** [comment]
Referring to this issue to the the landing page as the tech here proposed must be the core for the LP

[Link](https://github.com/w3b3d3v/web3task-lp/issues/1)

**Comment by 0xneves** [comment]
This task is completed as in the Landing Page is blocking the subsequent development of visual identity and components
