### ISSUE TITLE
refactor: remove react-router-dom to next

### ISSUE THREAD

**Issue by heronlancellot** [w3b3d3v/web3task-front#161]
- Change all the react-router-dom to use next

![Image](https://github.com/w3b3d3v/web3task-front/assets/57544272/a6c8b681-a599-4790-9af5-4fa6721d5998)

**Comment by diegosano** [comment]
@heronlancellot can I work on this one?

**Comment by heronlancellot** [comment]
hey @diegosano  ! assigned to you

**Comment by heronlancellot** [comment]
Closed by #168
