### ISSUE TITLE
feat: create Alchemy Provider to Web3task-Frontend

### ISSUE THREAD

**Issue by heronlancellot** [w3b3d3v/web3task-front#162]
Proposal: 

- Create a Alchemy Account to use the Alchemyt Provider in application
![Image](https://github.com/w3b3d3v/web3task-front/assets/57544272/44070a06-34c9-4f99-90f4-a82fa10e3e51)

- Create the web3task-front website using the Web3Dev repository, we already have an deployed website but isn't from web3dev repository.

**Comment by 0xdev3dl** [comment]
@0xneves  will be responsible for carrying out this task and the design of the LP is finalized and we can proceed to the next steps

**Comment by annabida** [comment]
Why not use public RPCs? @Guboehm @0xneves

**Comment by Guboehm** [comment]
At the moment it doesn't make sense for the project
