### ISSUE TITLE
feat: create validations for data in form

### ISSUE THREAD

**Issue by 0xneves** [w3b3d3v/web3task-front#17]
Create typing for data in form to handle possible errors and unexpected behavior.
When typing wrong values in the form such as letters that are supposed to be big int, an error will consume the app.

Proposal: 
Allows for decent typings in the form with enough error handlings

**Comment by durdsvianna** [comment]
closes #17

**Comment by 0xneves** [comment]
This was already made. I also added more stuff in #97
