### ISSUE TITLE
Elements of first connection

### ISSUE THREAD

**Issue by Guboehm** [w3b3d3v/web3task-front#175]
We need a design for the user's first wallet connection.
Intuitive images and texts are welcome.
Example:
![image](https://github.com/w3b3d3v/web3task-front/assets/32460314/72ebad62-f608-4851-94e9-48ce0c969ddd)
![image](https://github.com/w3b3d3v/web3task-front/assets/32460314/eb6a861a-c265-4b6b-bce1-20a6db0ecabc)

**Comment by 0xdev3dl** [comment]
![image](https://github.com/w3b3d3v/web3task-front/assets/101841063/11df3730-8661-4944-bb05-22428da0f807)

**Comment by Guboehm** [comment]
tks
