### ISSUE TITLE
directional links to place on the LP

### ISSUE THREAD

**Issue by 0xdev3dl** [w3b3d3v/web3task-front#176]
task for the member @Hardsys-Andre

**Twitter:** https://twitter.com/web3task_
**Linktree:** https://linktr.ee/web3task?utm_source=linktree_profile_share&ltsid=bd5b2288-989c-4719-9605-c5be37875792
**Discord Web3dev:** https://discord.gg/Zm6aEafv
**Documentation:** https://web3task.gitbook.io/web3task

**Comment by Guboehm** [comment]
Task completed
