### ISSUE TITLE
Should We Fork OnlyDust?

### ISSUE THREAD

**Issue by nomadbitcoin** [w3b3d3v/web3task-front#179]
- [x] Conduct a comprehensive feasibility assessment for forking the OnlyDust structure, including both frontend and backend components.

**Comment by nomadbitcoin** [comment]
### Issue: Should we fork OnlyDust?

I have evaluated the OnlyDust codebase, which comprises the following four repositories:

- [marketplace-frontend](https://github.com/onlydustxyz/marketplace-frontend)
- [marketplace-api](https://github.com/onlydustxyz/marketplace-api)
- [marketplace-indexer](https://github.com/onlydustxyz/marketplace-indexer)
- [marketplace-backend](https://github.com/onlydustxyz/marketplace-backend)

Given that the project is maintained by over 30 professionals, I believe it is not feasible for us to fork the project. While the project contains almost everything we aim to build, it lacks a payment module, presenting a technical challenge. Therefore, I recommend using OnlyDust as a reference for any issues we encounter while developing our own solution.

**Comment by nomadbitcoin** [comment]
### Summary of the App:

**Home Page:**
- Search Projects with filters for tags, ecosystems, and technologies.
- Sort options by contributors, project name, or trending status.

**Project Page:**
- Displays project name, photo, description, and tags.
- Details include project leads, contributors, ecosystems, sponsors, and technologies.
- Lists repositories and issues with labels, repo links, and application buttons.
- Actions: Sponsor project, get in touch, apply.

**Contributors Page:**
- Lists all contributors.

**Contributor Profile Page:**
- Shows detailed contributor information, activity, and work distribution.

**Hackathons Page:**
- Lists previous and upcoming hackathons.

**Contributions Page:**
- Tracks contributions (in progress, completed, canceled).

**Rewards Page:**
- Displays rewarded and pending amounts, filters by dates, projects, and currencies.

**Profile Menu:**
- Manage account, public profile, feedback, terms, privacy, log-out.

**Manage Account Page:**
- Connect GitHub, update profile details, set time availability, job search status, and payout preferences.

**Payment Profile Page:**
- Payment methods, company information, and invoices.

More details about the features available: https://www.evernote.com/shard/s354/sh/83e9d44f-cb47-b0e5-5a61-ab18a8dd6199/KNVwCxxt1TfHF3VvrkG4vj5lSQt9m_kng0JQ-c5XUYsri4wCOvOBExJ-TQ

**Comment by Guboehm** [comment]
I analyzed the repository and tried to run the project but without success there is a high complexity layer to run and with several dependencies.
In short, we can use the project as a guide.
Thanks for the documentation, we can start from these principles.
