### ISSUE TITLE
feat: Add Ethers.js support and remove Viem

### ISSUE THREAD

**Issue by 0xneves** [w3b3d3v/web3task-front#18]
Viem is not communicating well with the simplicity we need for the MvP.

Proposal:
Remove Viem and use Ethers instead to prepare and call transactions

**Comment by 0xneves** [comment]
Viem libraries were not allowed to install ethers. Wagmi was still needed, so a cleanup of the packages took place and now ethers is running smoothly.

**Comment by jxom** [comment]
Curious what you mean here?

**Comment by durdsvianna** [comment]
#19  - included ethers.js 5.7.2 + wagmi and validated with createTask in contract.
