### ISSUE TITLE
feat: display tasks into the front page and add filter properties according to Figma

### ISSUE THREAD

**Issue by 0xneves** [w3b3d3v/web3task-front#20]
Proposal:
- Display the main task page according to the [Figma Design](https://www.figma.com/file/UDGGqo8K53CiYYpGutoVuH/PodLabs?type=design&node-id=0-1&mode=design)
- ~Filter Task properties~
- ~Pagination~
- ~Redirect to TaskInfo~

**Comment by 0xneves** [comment]
For better address displaying we use the following format: (for assignee)
0xABCD...ABCD

**Comment by heronlancellot** [comment]
#20-feat-display-tasks-into-the-front-page-and-add-filter-properties-according-to-figma-1
Implemented the main task page with getMultiTasks() *Multicall ~ just need few adjustes in CSS

**Comment by 0xneves** [comment]
I'm cutting the  filter part of this issue to better fragment its execution. Pagination and redirection will also be removed.

**Comment by heronlancellot** [comment]
#36 Implemented the main task page
