### ISSUE TITLE
feat: related images, design of presentation and optimization of quality of view

### ISSUE THREAD

**Issue by 0xneves** [w3b3d3v/web3task-front#25]

**Comment by 0xdev3dl** [comment]
I am interested

**Comment by 0xdev3dl** [comment]
[Logo Web3task.zip](https://github.com/w3b3d3v/web3task-front/files/12773492/Logo.Web3task.zip)

**Comment by heronlancellot** [comment]
@andressa-cabral please update logo to light mode context :)

**Comment by 0xdev3dl** [comment]
updated
[logo web3task.zip](https://github.com/w3b3d3v/web3task-front/files/12774818/logo.web3task.zip)

**Comment by heronlancellot** [comment]
Implemented new updated design logo in #42
