### ISSUE TITLE
feat: create search filters for the task components from the main page and the profile page accordingly to Figma

### ISSUE THREAD

**Issue by 0xneves** [w3b3d3v/web3task-front#34]
feat: 

Accordingly to  [Figma](https://www.figma.com/file/UDGGqo8K53CiYYpGutoVuH/PodLabs?type=design&node-id=0-1&mode=design), reproduce the filter options, applying only on the ones being showed between each pagination setting, ie.: assuming you have 5x4 squares of NFTs being displayed, if the title has the word `PodLabs` in it, it will filter for the `Title` option looking for the regex of PodLabs.

Goals:
- Filter Title, AuthorizedRole, CreatorRole, Reward and DueDate.
- Use regex to match values

**Comment by diegosano** [comment]
@0xneves I would like to work in this one

**Comment by 0xneves** [comment]
Hey Diego, awesome to hear that!! Just assignee you to the task!

Please contact me in case you have any issues!!
