### ISSUE TITLE
feat: Solana Wallet login with Phantom Wallet

### ISSUE THREAD

**Issue by 0xneves** [w3b3d3v/web3task-front#44]
Proposal:
Implement the Phantom Wallet for the Solana Blockchain in the front end

**Comment by Dione-b** [comment]
I can implement this feature.

**Comment by 0xneves** [comment]
I've assigned you to this task Dione! Let's build this feature Asap, Solana is watching! 👀

**Comment by 0xneves** [comment]
https://medium.com/@jorge_londono_31005/intro-to-solana-webapp-development-with-react-typescript-phantom-ca2724d1fa22

**Comment by 0xneves** [comment]
Bumping this to know the current status @Dione-b

**Comment by Dione-b** [comment]
> Bumping this to know the current status @Dione-b

I'm having difficulty just validating the credential. If there is someone who wants to take over the task, I have no problem giving up my place.

**Comment by 0xneves** [comment]
I will reassign it them

**Comment by 0xneves** [comment]
We are in need of this solution! Apply to help please >.<

**Comment by 0xneves** [comment]
We opened a issue to look for the adequate dev at this [link](https://github.com/w3b3d3v/web3task-org/issues/26)

**Comment by Guboehm** [comment]
At the moment it doesn't make sense for the project
