### ISSUE TITLE
review: unused front-end liens of code must be deleted in other to enhance overall performance

### ISSUE THREAD

**Issue by 0xneves** [w3b3d3v/web3task-front#46]
There are a lot of things to remove from the current front-end.

Proposal:
-For instance the sidebar menu in the `overview` named route.
-Review the code looking for unused lines of code and propose the deletion of the unused code, letting us know -why.

Please help this issue become and overall audit of unused code.

**Comment by alotth** [comment]
I wanna do that task

**Comment by 0xneves** [comment]
I just talked to @andersonlthome and he would like to give this task a go to help eliminate unused lines of code.
