### ISSUE TITLE
feat: deploy front-end in Vercel

### ISSUE THREAD

**Issue by 0xneves** [w3b3d3v/web3task-front#47]
I will provide access to the Vercel account for the one willing to help configure and deploy the app into Vercel.

**Comment by durdsvianna** [comment]
For now it is deployed on my forked repository.
Deployment file for Vercel was created on project.

![Image](https://github.com/w3b3d3v/web3task-front/assets/19876786/b9f8df72-89b8-44c9-bad1-f2419974ceea)

URL do ambiente UAT (dev): 
https://web3task-front-uat.vercel.app/
