### ISSUE TITLE
fix: do a better pathing for the application

### ISSUE THREAD

**Issue by 0xneves** [w3b3d3v/web3task-front#49]
Following is an example of a path that needs fixing:
![Image](https://github.com/w3b3d3v/web3task-front/assets/90667119/859c944b-6548-4d56-bb47-01a68cddec60)

Need more cohesion with the overall architecture.
Need someone to fix the above and spot new ones, this can be done by thoroughly checking all file names and folder names.

Definition of done:
- Fix the recommended path
- Check every single filename and folder name
- Comment on this card every non-sense path with suggestions
- Fix the suggestions and the problems derived by its changes

**Comment by durdsvianna** [comment]
1. -Fixed recommended path as follows:

![Image](https://github.com/w3b3d3v/web3task-front/assets/19876786/748f8860-75bb-421e-ae33-98ecf7894a6f)


2. organized content page components and components
3. organized name of artifacts
