### ISSUE TITLE
feat: display cards (empty)  in both explore and profile page prior to loading the tasks

### ISSUE THREAD

**Issue by 0xneves** [w3b3d3v/web3task-front#53]
We cannot wait for the tasks to be loaded to actually create smoothness in the user experience. We must load de empty cards, and set up a loading for every field that is waiting for data which is async from the rest of the loadings.

Proposal:
- Make a standard default, empty task, which will be the PLACEHOLDER
- When the multicall fetches all tasks for the page are ready, then display it accordingly

**Comment by alotth** [comment]
I'm interested in doing that task, but how many loading-cards do you think we have to show?

**Comment by 0xneves** [comment]
For the MvP, only 20 fixed per page

I'm assigning this to @andersonlthome
