### ISSUE TITLE
feat: suggest branding design for overall dApp

### ISSUE THREAD

**Issue by 0xneves** [w3b3d3v/web3task-front#54]
Proposal:
- We need more synergy for the website, need elements that connect everywhere
- Find typographies to use, literally, everywhere (using Arial vibes for now)
- Get a lot of colors please

**Comment by 0xneves** [comment]
Talked to @andressa-cabral and she wants to do this task

**Comment by 0xneves** [comment]
We need Font file for the website asap 
Let's look for: Public Sans

**Comment by heronlancellot** [comment]
@0xneves  #92  Added Public Sans Typography in all Application

**Comment by 0xneves** [comment]
Awesome, let's close this!
