### ISSUE TITLE
Feat: Pagination Component dynamic count Pages

### ISSUE THREAD

**Issue by heronlancellot** [w3b3d3v/web3task-front#56]
2.  Because we don't know the number of all Tasks, the pagination **count** should be incremental. Not Fixed like that:
![image](https://github.com/w3b3d3v/web3task-front/assets/57544272/c52ab6c0-ff6c-4ec5-8c4c-fea2861b497b)
2.1 
![image](https://github.com/w3b3d3v/web3task-front/assets/57544272/ca4fb976-7123-4bd7-83a4-8fdd10d2f362)
If the tasks displayed on the front end are smaller than they should be in tasksPerPage, we know the correct maxPage and that would be the count.

Proposal: Verify the correct count using the multitasks array. We should be able to navigate between pagination clicking in arrow or just clicking in the number of the page.

**Comment by durdsvianna** [comment]
Done.
