### ISSUE TITLE
Feat: Adjust Header correctly

### ISSUE THREAD

**Issue by heronlancellot** [w3b3d3v/web3task-front#62]
- Need be resposive
- UserBox component need check access control by connected wallet 
- Need abbreviate wallet address

**Comment by viniblack** [comment]
Can provide more information about what needs to be done

**Comment by heronlancellot** [comment]
@viniblack off course!
The Header isn't working Responsive 
Need Adjust to fit well in all devices 
 - Suggestion: Use Theme from Material UI to create a good fit like using for example theme.spacing or theme.breakpoints

![Image](https://github.com/w3b3d3v/web3task-front/assets/57544272/37f09609-5245-4ea3-b674-0b065a5168aa)

If it helps, check the previous commits on dev to see how SideBarLayout was working :)

**Comment by durdsvianna** [comment]
Done.

**Comment by heronlancellot** [comment]
@durdsvianna please Adjust the header responsibility


![Image](https://github.com/w3b3d3v/web3task-front/assets/57544272/c8e0d80c-8cf8-4d8a-9dcb-3e29e7598bd7)
