### ISSUE TITLE
feat: subgraph must be working in localhost and mainnet and have a guide showing how to run it

### ISSUE THREAD

**Issue by RafaDSan** [w3b3d3v/web3task-front#91]
NOTE: Needs issue resolved: https://github.com/w3b3d3v/web3task-contracts/issues/10

https://github.com/w3b3d3v/web3task-contracts/tree/main/contracts
The events can be seen in the contract architecture.

Proposal:

Set up the subgraph for the livenet and localhost
Make sure the queries are working by testing them to fetch data like the below:
-- Get the most recent tasks
-- Task creator address displayed on the events
-- Display recent Roles set or Operators set by admins
-- Show us your creativity!!
Eventually it will all be using features-like subgraph, so go nuts!

**Comment by 0xneves** [comment]
Duplicated from the pull request and on the wrong repository section
Moved to the contracts repository with the pull request 31
