### ISSUE TITLE
feat: endDate field is not in the US format in createTask.

### ISSUE THREAD

**Issue by RafaDSan** [w3b3d3v/web3task-front#93]
The date format should be standardized. As the Web3Task is aiming to become a global platform, the date fields should follow a standard format, such as MM/DD/YYYY.

![Image](https://github.com/w3b3d3v/web3task-front/assets/102108966/66c4cd99-dae5-4dd1-a219-b60d19f8936f)

Resolution: 

End Date should be displayed in the following format: MM/DD/YYYY

**Comment by 0xneves** [comment]
This was closed in #95
